server:
  port: 8083

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3307/customerrelationship?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update