server:
  port:8083

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3307/customerrelationship
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update


  ---
